package by.epam.dao.impl;

public class SQLRequest {
	
	public static final String SELECT_CHECK_USER = "SELECT users.username, users.password, users.isDelete, users.email, users.phoneNumber, users.address, users.photo, roles.role, persons.typePerson FROM allservices.users, allservices.roles, allservices.persons WHERE roles.id=users.roles_id AND persons.id=users.persons_id AND users.username=? AND users.password=?";
	public static final String SELECT_CHECK_PASSWORD = "SELECT users.username FROM allservices.users WHERE users.password=?";
	public static final String SELECT_SERVICE_STAFF = "SELECT servicestaff.name, servicestaff.surname FROM allservices.users, allservices.servicestaff WHERE users.id=servicestaff.users_id AND users.username=?";
	public static final String SELECT_CUSTOMER = "SELECT ownerships.formOwnership FROM allservices.users, allservices.customers, allservices.ownerships WHERE ownerships.id=customers.ownerships_id AND users.id=customers.users_id AND users.username=?";
	public static final String SELECT_CUSTOMER_NATURAL = "SELECT infonaturalcustomers.name, infonaturalcustomers.surname FROM allservices.infonaturalcustomers, allservices.customers, allservices.users WHERE customers.id=infonaturalcustomers.customers_id AND users.id=customers.users_id AND users.username=?";
	public static final String SELECT_CUSTOMER_LEGAL = "SELECT infolegalcustomers.name, infolegalcustomers.surname, infolegalcustomers.requisites, infolegalcustomers.copyregistration FROM allservices.infolegalcustomers, allservices.customers, allservices.users WHERE customers.id=infolegalcustomers.customers_id AND users.id=customers.users_id AND users.username=?";
	public static final String SELECT_CUSTOMER_COMPANY = "SELECT infocompanycustomers.nameCompany, infocompanycustomers.nameAgent, infocompanycustomers.surnameAgent, infocompanycustomers.requisites, infocompanycustomers.description FROM allservices.infocompanycustomers, allservices.customers, allservices.users WHERE customers.id=infocompanycustomers.customers_id AND users.id=customers.users_id AND users.username=?";
	public static final String SELECT_PERFORMER = "SELECT performers.requisites, ownerships.formOwnership FROM allservices.users, allservices.performers, allservices.ownerships WHERE ownerships.id=performers.ownerships_id AND users.id=performers.users_id AND users.username=?";
	public static final String SELECT_PERFORMER_LEGAL = "SELECT infolegalperformers.name, infolegalperformers.surname, infolegalperformers.copyRegistration FROM allservices.infolegalperformers, allservices.performers, allservices.users WHERE performers.id=infolegalperformers.performers_id AND users.id=performers.users_id AND users.username=?";
	public static final String SELECT_PERFORMER_COMPANY = "SELECT infocompanyperformers.nameCompany, infocompanyperformers.nameAgent, infocompanyperformers.surnameAgent, infocompanyperformers.description FROM allservices.infocompanyperformers, allservices.performers, allservices.users WHERE performers.id=infocompanyperformers.performers_id AND users.id=performers.users_id AND users.username=?";
	public static final String SELECT_EXIST_USER = "SELECT users.username FROM allservices.users WHERE users.username=?";
	public static final String SELECT_ROLE_USER = "SELECT roles.id FROM allservices.roles, allservices.users WHERE roles.id=users.roles_id AND roles.role=?";
	public static final String SELECT_PERSON_USER = "SELECT persons.id FROM allservices.persons, allservices.users WHERE persons.id=users.persons_id AND persons.typePerson=?";
	public static final String SELECT_OWNERSHIP_USER = "SELECT ownerships.id FROM allservices.ownerships WHERE ownerships.formOwnership=?";
	public static final String CREATE_USER = "INSERT INTO allservices.users (users.username, users.password, users.isDelete, users.email, users.phoneNumber, users.address, users.photo, users.roles_id, users.persons_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
	public static final String CREATE_SERVICE_PERSON = "INSERT INTO allservices.serviceStaff (serviceStaff.name, serviceStaff.surname, serviceStaff.users_id) VALUES (?, ?, ?)";	
	public static final String CREATE_CUSTOMER_PERSON = "INSERT INTO allservices.customers (customers.ownerships_id, customers.users_id) VALUES (?, ?)";
	public static final String CREATE_CUSTOMER_NATURAL_PERSON = "INSERT INTO allservices.infoNaturalCustomers (infoNaturalCustomers.name, infoNaturalCustomers.surname, infoNaturalCustomers.customers_id) VALUES (?, ?, ?)";
	public static final String CREATE_CUSTOMER_LEGAL_PERSON = "INSERT INTO allservices.infoLegalCustomers (infoLegalCustomers.name, infoLegalCustomers.surname, infoLegalCustomers.requisites, infoLegalCustomers.copyRegistration, infoLegalCustomers.customers_id) VALUES (?, ?, ?, ?, ?)";
	public static final String CREATE_CUSTOMER_COMPANY_PERSON = "INSERT INTO allservices.infoCompanyCustomers (infoCompanyCustomers.nameCompany, infoCompanyCustomers.nameAgent, infoCompanyCustomers.surnameAgent, infoCompanyCustomers.requisites, infoCompanyCustomers.description, infoCompanyCustomers.customers_id) VALUES (?, ?, ?, ?, ?, ?)";
	public static final String CREATE_PERFORMER_PERSON = "INSERT INTO allservices.performers (performers.requisites, performers.ownerships_id, performers.users_id) VALUES (?, ?, ?)";
	public static final String CREATE_PERFORMER_LEGAL_PERSON = "INSERT INTO allservices.infoLegalPerformers (infoLegalPerformers.name, infoLegalPerformers.surname, infoLegalPerformers.copyRegistration, infoLegalPerformers.performers_id) VALUES (?, ?, ?, ?)";
	public static final String CREATE_PERFORMER_COMPANY_PERSON = "INSERT INTO allservices.infoCompanyPerformers (infoCompanyPerformers.nameCompany, infoCompanyPerformers.nameAgent, infoCompanyPerformers.surnameAgent, infoCompanyPerformers.description, infoCompanyPerformers.performers_id) VALUES (?, ?, ?, ?, ?)";
	public static final String UPDATE_SERVICE_PERSON = "UPDATE allservices.users, allservices.serviceStaff SET users.email=?, users.phoneNumber=?, users.address=?, users.photo=?, serviceStaff.name=?, serviceStaff.surname=? WHERE users.id=servicestaff.users_id AND users.username=?";
	public static final String UPDATE_CUSTOMER_NATURAL_PERSON = "UPDATE allservices.users, allservices.customers, allservices.infoNaturalCustomers SET users.email=?, users.phoneNumber=?, users.address=?, users.photo=?, infoNaturalCustomers.name=?, infoNaturalCustomers.surname=? WHERE users.id=customers.users_id AND customers.id=infoNaturalCustomers.customers_id AND users.username=?";
	public static final String UPDATE_CUSTOMER_LEGAL_PERSON = "UPDATE allservices.users, allservices.customers, allservices.infoLegalCustomers SET users.email=?, users.phoneNumber=?, users.address=?, users.photo=?, infoLegalCustomers.name=?, infoLegalCustomers.surname=?, infoLegalCustomers.requisites=?, infoLegalCustomers.copyRegistration=? WHERE users.id=customers.users_id AND customers.id=infoLegalCustomers.customers_id AND users.username=?";
	public static final String UPDATE_CUSTOMER_COMPANY_PERSON = "UPDATE allservices.users, allservices.customers, allservices.infoCompanyCustomers SET users.email=?, users.phoneNumber=?, users.address=?, users.photo=?, infoCompanyCustomers.nameCompany=?, infoCompanyCustomers.nameAgent=?, infoCompanyCustomers.surnameAgent=?, infoCompanyCustomers.requisites=?, infoCompanyCustomers.description=? WHERE users.id=customers.users_id AND customers.id=infoCompanyCustomers.customers_id AND users.username=?";
	public static final String UPDATE_PERFORMER_LEGAL_PERSON = "UPDATE allservices.users, allservices.performers, allservices.infolegalperformers SET users.email=?, users.phoneNumber=?, users.address=?, users.photo=?, performers.requisites=?, infolegalperformers.name=?, infolegalperformers.surname=?, infolegalperformers.copyRegistration=? WHERE users.id=performers.users_id AND performers.id=infolegalperformers.performers_id AND users.username=?";
	public static final String UPDATE_PERFORMER_COMPANY_PERSON = "UPDATE allservices.users, allservices.performers, allservices.infocompanyperformers SET users.email=?, users.phoneNumber=?, users.address=?, users.photo=?, performers.requisites=?, infocompanyperformers.nameCompany=?, infocompanyperformers.nameAgent=?, infocompanyperformers.surnameAgent=?, infocompanyperformers.description=? WHERE users.id=performers.users_id AND performers.id=infocompanyperformers.performers_id AND users.username=?";
	public static final String UPDATE_PASSWORD = "UPDATE allservices.users SET users.password=? WHERE users.username=?";
	
	
	private SQLRequest() {
	}	
}
