package by.epam.dao.impl;

public final class SQLRequest {
	
	public static final String SELECT_CHECK_USER = "SELECT users.username, users.password, users.isDelete, users.email, users.phoneNumber, users.address, users.photo, roles.role, persons.typePerson FROM allservices.users, allservices.roles, allservices.persons WHERE roles.id=users.roles_id AND persons.id=users.persons_id AND users.username=? AND users.password=?";
	public static final String SELECT_USER_BY_USERNAME = "SELECT users.username, users.isDelete, users.email, users.phoneNumber, users.address, users.photo, roles.role, persons.typePerson FROM allservices.users, allservices.roles, allservices.persons WHERE roles.id=users.roles_id AND persons.id=users.persons_id AND users.username=?";
	public static final String SELECT_CHECK_PASSWORD = "SELECT users.username FROM allservices.users WHERE users.password=?";
	public static final String SELECT_SERVICE_STAFF = "SELECT servicestaff.name, servicestaff.surname FROM allservices.users, allservices.servicestaff WHERE users.id=servicestaff.users_id AND users.username=?";
	public static final String SELECT_CUSTOMER = "SELECT ownerships.formOwnership FROM allservices.users, allservices.customers, allservices.ownerships WHERE ownerships.id=customers.ownerships_id AND users.id=customers.users_id AND users.username=?";
	public static final String SELECT_CUSTOMER_NATURAL = "SELECT infonaturalcustomers.name, infonaturalcustomers.surname FROM allservices.infonaturalcustomers, allservices.customers, allservices.users WHERE customers.id=infonaturalcustomers.customers_id AND users.id=customers.users_id AND users.username=?";
	public static final String SELECT_CUSTOMER_LEGAL = "SELECT infolegalcustomers.name, infolegalcustomers.surname, infolegalcustomers.requisites, infolegalcustomers.copyregistration FROM allservices.infolegalcustomers, allservices.customers, allservices.users WHERE customers.id=infolegalcustomers.customers_id AND users.id=customers.users_id AND users.username=?";
	public static final String SELECT_CUSTOMER_COMPANY = "SELECT infocompanycustomers.nameCompany, infocompanycustomers.nameAgent, infocompanycustomers.surnameAgent, infocompanycustomers.requisites, infocompanycustomers.description FROM allservices.infocompanycustomers, allservices.customers, allservices.users WHERE customers.id=infocompanycustomers.customers_id AND users.id=customers.users_id AND users.username=?";
	public static final String SELECT_PERFORMER = "SELECT performers.requisites, ownerships.formOwnership FROM allservices.users, allservices.performers, allservices.ownerships WHERE ownerships.id=performers.ownerships_id AND users.id=performers.users_id AND users.username=?";
	public static final String SELECT_PERFORMER_LEGAL = "SELECT infolegalperformers.name, infolegalperformers.surname, infolegalperformers.copyRegistration FROM allservices.infolegalperformers, allservices.performers, allservices.users WHERE performers.id=infolegalperformers.performers_id AND users.id=performers.users_id AND users.username=?";
	public static final String SELECT_PERFORMER_COMPANY = "SELECT infocompanyperformers.nameCompany, infocompanyperformers.nameAgent, infocompanyperformers.surnameAgent, infocompanyperformers.description FROM allservices.infocompanyperformers, allservices.performers, allservices.users WHERE performers.id=infocompanyperformers.performers_id AND users.id=performers.users_id AND users.username=?";
	public static final String SELECT_EXIST_USER = "SELECT users.username FROM allservices.users WHERE users.username=?";
	public static final String SELECT_ROLE_USER = "SELECT roles.id FROM allservices.roles, allservices.users WHERE roles.id=users.roles_id AND roles.role=?";
	public static final String SELECT_PERSON_USER = "SELECT persons.id FROM allservices.persons, allservices.users WHERE persons.id=users.persons_id AND persons.typePerson=?";
	public static final String SELECT_OWNERSHIP_USER = "SELECT ownerships.id FROM allservices.ownerships WHERE ownerships.formOwnership=?";
	public static final String SELECT_ALL_USER = "SELECT SQL_CALC_FOUND_ROWS * FROM allservices.users, allservices.roles, allservices.persons WHERE roles.id=users.roles_id AND persons.id=users.persons_id AND users.isDelete='false' LIMIT ?, ?";
	public static final String SELECT_COUNT_USER = "SELECT FOUND_ROWS()";
	public static final String SELECT_USER_ID = "SELECT users.id FROM allservices.users WHERE users.username=?";
	public static final String SELECT_ALL_ORDER_OF_USER = "SELECT SQL_CALC_FOUND_ROWS orders.id, orders.title, orders.description, orders.subtypeSpecialization, orders.status, orders.address, orders.endDate, orders.dateOfCreating, orders.attachments, orders.performer, orders.specialization_id, specialization.descriptionru, specialization.activities FROM allservices.users, allservices.orders, allservices.specialization WHERE users.id=orders.users_id AND specialization.id=orders.specialization_id AND users.username=? LIMIT ?, ?";
	public static final String SELECT_ALL_ORDERS_OF_USERS = "SELECT SQL_CALC_FOUND_ROWS orders.id, orders.title, orders.description, orders.subtypeSpecialization, orders.status, orders.address, orders.endDate, orders.dateOfCreating, orders.attachments, orders.performer, orders.specialization_id, specialization.descriptionru, specialization.activities FROM allservices.users, allservices.orders, allservices.specialization WHERE users.id=orders.users_id AND specialization.id=orders.specialization_id AND orders.status='choose' LIMIT ?, ?";
	public static final String SELECT_COUNT_ORDER = "SELECT FOUND_ROWS()";
	public static final String SELECT_ORDER_OF_USER = "SELECT orders.id, orders.title, orders.description, orders.subtypeSpecialization, orders.status, orders.address, orders.endDate, orders.dateOfCreating, orders.attachments, orders.performer, orders.specialization_id, specialization.descriptionru, specialization.activities FROM allservices.users, allservices.orders, allservices.specialization WHERE users.id=orders.users_id AND specialization.id=orders.specialization_id AND orders.id=?";
	public static final String SELECT_ALL_OFFERING_OF_ORDER = "SELECT users.username, users.password, users.isDelete, users.email, users.phoneNumber, users.address, users.photo, roles.role, persons.typePerson, offering.description, orders.title FROM allservices.users, allservices.roles, allservices.persons, allservices.offering, allservices.performers, allservices.orders WHERE roles.id=users.roles_id AND persons.id=users.persons_id AND users.id=performers.users_id AND performers.id=offering.performers_id AND orders.id=offering.orders_id AND orders.id=? LIMIT ?, ?";
	public static final String SELECT_ALL_OFFERING_BY_ID_ORDER = "SELECT offering.id, offering.description, offering.username FROM allservices.offering, allservices.orders WHERE orders.id=offering.orders_id AND orders.id=?";
	
	public static final String SELECT_SPECIALIZATION_TRUCKING_EN = "SELECT specialization.descriptionen, truckingindustry.typesTruckingEn FROM allservices.specialization, allservices.truckingindustry WHERE specialization.id=truckingindustry.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_TRUCKING_RU = "SELECT specialization.descriptionru, truckingindustry.typesTruckingRu FROM allservices.specialization, allservices.truckingindustry WHERE specialization.id=truckingindustry.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_REPAIR_EN = "SELECT specialization.descriptionen, repairandconstruction.typesRepairAndConstructionEn FROM allservices.specialization, allservices.repairandconstruction WHERE specialization.id=repairandconstruction.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_REPAIR_RU = "SELECT specialization.descriptionru, repairandconstruction.typesRepairAndConstructionRu FROM allservices.specialization, allservices.repairandconstruction WHERE specialization.id=repairandconstruction.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_COURIER_EN = "SELECT specialization.descriptionen, courierservices.typeCourierServicesEn FROM allservices.specialization, allservices.courierservices WHERE specialization.id=courierservices.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_COURIER_RU = "SELECT specialization.descriptionru, courierservices.typeCourierServicesRu FROM allservices.specialization, allservices.courierservices WHERE specialization.id=courierservices.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_CLEANING_EN = "SELECT specialization.descriptionen, cleaningandhelps.typeCleaningAndHelpsEn FROM allservices.specialization, allservices.cleaningandhelps WHERE specialization.id=cleaningandhelps.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_CLEANING_RU = "SELECT specialization.descriptionru, cleaningandhelps.typeCleaningAndHelpsRu FROM allservices.specialization, allservices.cleaningandhelps WHERE specialization.id=cleaningandhelps.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_COMPUTER_EN = "SELECT specialization.descriptionen, computerhelps.typrComputerHelpsEn FROM allservices.specialization, allservices.computerhelps WHERE specialization.id=computerhelps.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_COMPUTER_RU = "SELECT specialization.descriptionru, computerhelps.typrComputerHelpsRu FROM allservices.specialization, allservices.computerhelps WHERE specialization.id=computerhelps.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_EVENTS_EN = "SELECT specialization.descriptionen, eventsandpromotions.typeEventsAndPromotionsEn FROM allservices.specialization, allservices.eventsandpromotions WHERE specialization.id=eventsandpromotions.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_EVENTS_RU = "SELECT specialization.descriptionru, eventsandpromotions.typeEventsAndPromotionsRu FROM allservices.specialization, allservices.eventsandpromotions WHERE specialization.id=eventsandpromotions.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_DESIGN_EN = "SELECT specialization.descriptionen, design.typeDesignEn FROM allservices.specialization, allservices.design WHERE specialization.id=design.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_DESIGN_RU = "SELECT specialization.descriptionru, design.typeDesignRu FROM allservices.specialization, allservices.design WHERE specialization.id=design.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_PHOTO_EN = "SELECT specialization.descriptionen, photoandvideoservices.typePhotoAndVideoServicesEn FROM allservices.specialization, allservices.photoandvideoservices WHERE specialization.id=photoandvideoservices.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_PHOTO_RU = "SELECT specialization.descriptionru, photoandvideoservices.typePhotoAndVideoServicesRu FROM allservices.specialization, allservices.photoandvideoservices WHERE specialization.id=photoandvideoservices.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_WEB_EN = "SELECT specialization.descriptionen, webdeveloping.typeWebDevelopingEn FROM allservices.specialization, allservices.webdeveloping WHERE specialization.id=webdeveloping.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_WEB_RU = "SELECT specialization.descriptionru, webdeveloping.typeWebDevelopingRu FROM allservices.specialization, allservices.webdeveloping WHERE specialization.id=webdeveloping.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_INSTALL_EN = "SELECT specialization.descriptionen, installandrepairequipment.typeInstallAndRepairEquipmentEn FROM allservices.specialization, allservices.installandrepairequipment WHERE specialization.id=installandrepairequipment.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_INSTALL_RU = "SELECT specialization.descriptionru, installandrepairequipment.typeInstallAndRepairEquipmentRu FROM allservices.specialization, allservices.installandrepairequipment WHERE specialization.id=installandrepairequipment.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_BEAUTY_EN = "SELECT specialization.descriptionen, beautyandhealth.typeBeautyAndHealthEn FROM allservices.specialization, allservices.beautyandhealth WHERE specialization.id=beautyandhealth.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_BEAUTY_RU = "SELECT specialization.descriptionru, beautyandhealth.typeBeautyAndHealthRu FROM allservices.specialization, allservices.beautyandhealth WHERE specialization.id=beautyandhealth.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_LEGAL_EN = "SELECT specialization.descriptionen, legalassistance.typeLegalAssistanceEn FROM allservices.specialization, allservices.legalassistance WHERE specialization.id=legalassistance.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_LEGAL_RU = "SELECT specialization.descriptionru, legalassistance.typeLegalAssistanceRu FROM allservices.specialization, allservices.legalassistance WHERE specialization.id=legalassistance.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_EDUCATION_EN = "SELECT specialization.descriptionen, education.typeEducationEn FROM allservices.specialization, allservices.education WHERE specialization.id=education.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_EDUCATION_RU = "SELECT specialization.descriptionru, education.typeEducationRu FROM allservices.specialization, allservices.education WHERE specialization.id=education.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_REPAIR_TRANSPORT_EN = "SELECT specialization.descriptionen, repairtransport.typeRepairTransportEn FROM allservices.specialization, allservices.repairtransport WHERE specialization.id=repairtransport.specialization_id AND specialization.activities=?";
	public static final String SELECT_SPECIALIZATION_REPAIR_TRANSPORT_RU = "SELECT specialization.descriptionru, repairtransport.typeRepairTransportRu FROM allservices.specialization, allservices.repairtransport WHERE specialization.id=repairtransport.specialization_id AND specialization.activities=?";
	
	
	public static final String CREATE_USER = "INSERT INTO allservices.users (users.username, users.password, users.isDelete, users.email, users.phoneNumber, users.address, users.photo, users.roles_id, users.persons_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
	public static final String CREATE_SERVICE_PERSON = "INSERT INTO allservices.serviceStaff (serviceStaff.name, serviceStaff.surname, serviceStaff.users_id) VALUES (?, ?, ?)";	
	public static final String CREATE_CUSTOMER_PERSON = "INSERT INTO allservices.customers (customers.ownerships_id, customers.users_id) VALUES (?, ?)";
	public static final String CREATE_CUSTOMER_NATURAL_PERSON = "INSERT INTO allservices.infoNaturalCustomers (infoNaturalCustomers.name, infoNaturalCustomers.surname, infoNaturalCustomers.customers_id) VALUES (?, ?, ?)";
	public static final String CREATE_CUSTOMER_LEGAL_PERSON = "INSERT INTO allservices.infoLegalCustomers (infoLegalCustomers.name, infoLegalCustomers.surname, infoLegalCustomers.requisites, infoLegalCustomers.copyRegistration, infoLegalCustomers.customers_id) VALUES (?, ?, ?, ?, ?)";
	public static final String CREATE_CUSTOMER_COMPANY_PERSON = "INSERT INTO allservices.infoCompanyCustomers (infoCompanyCustomers.nameCompany, infoCompanyCustomers.nameAgent, infoCompanyCustomers.surnameAgent, infoCompanyCustomers.requisites, infoCompanyCustomers.description, infoCompanyCustomers.customers_id) VALUES (?, ?, ?, ?, ?, ?)";
	public static final String CREATE_PERFORMER_PERSON = "INSERT INTO allservices.performers (performers.requisites, performers.ownerships_id, performers.users_id) VALUES (?, ?, ?)";
	public static final String CREATE_PERFORMER_LEGAL_PERSON = "INSERT INTO allservices.infoLegalPerformers (infoLegalPerformers.name, infoLegalPerformers.surname, infoLegalPerformers.copyRegistration, infoLegalPerformers.performers_id) VALUES (?, ?, ?, ?)";
	public static final String CREATE_PERFORMER_COMPANY_PERSON = "INSERT INTO allservices.infoCompanyPerformers (infoCompanyPerformers.nameCompany, infoCompanyPerformers.nameAgent, infoCompanyPerformers.surnameAgent, infoCompanyPerformers.description, infoCompanyPerformers.performers_id) VALUES (?, ?, ?, ?, ?)";
	public static final String UPDATE_SERVICE_PERSON = "UPDATE allservices.users, allservices.serviceStaff SET users.email=?, users.phoneNumber=?, users.address=?, users.photo=?, serviceStaff.name=?, serviceStaff.surname=? WHERE users.id=servicestaff.users_id AND users.username=?";
	public static final String UPDATE_CUSTOMER_NATURAL_PERSON = "UPDATE allservices.users, allservices.customers, allservices.infoNaturalCustomers SET users.email=?, users.phoneNumber=?, users.address=?, users.photo=?, infoNaturalCustomers.name=?, infoNaturalCustomers.surname=? WHERE users.id=customers.users_id AND customers.id=infoNaturalCustomers.customers_id AND users.username=?";
	public static final String UPDATE_CUSTOMER_LEGAL_PERSON = "UPDATE allservices.users, allservices.customers, allservices.infoLegalCustomers SET users.email=?, users.phoneNumber=?, users.address=?, users.photo=?, infoLegalCustomers.name=?, infoLegalCustomers.surname=?, infoLegalCustomers.requisites=?, infoLegalCustomers.copyRegistration=? WHERE users.id=customers.users_id AND customers.id=infoLegalCustomers.customers_id AND users.username=?";
	public static final String UPDATE_CUSTOMER_COMPANY_PERSON = "UPDATE allservices.users, allservices.customers, allservices.infoCompanyCustomers SET users.email=?, users.phoneNumber=?, users.address=?, users.photo=?, infoCompanyCustomers.nameCompany=?, infoCompanyCustomers.nameAgent=?, infoCompanyCustomers.surnameAgent=?, infoCompanyCustomers.requisites=?, infoCompanyCustomers.description=? WHERE users.id=customers.users_id AND customers.id=infoCompanyCustomers.customers_id AND users.username=?";
	public static final String UPDATE_PERFORMER_LEGAL_PERSON = "UPDATE allservices.users, allservices.performers, allservices.infolegalperformers SET users.email=?, users.phoneNumber=?, users.address=?, users.photo=?, performers.requisites=?, infolegalperformers.name=?, infolegalperformers.surname=?, infolegalperformers.copyRegistration=? WHERE users.id=performers.users_id AND performers.id=infolegalperformers.performers_id AND users.username=?";
	public static final String UPDATE_PERFORMER_COMPANY_PERSON = "UPDATE allservices.users, allservices.performers, allservices.infocompanyperformers SET users.email=?, users.phoneNumber=?, users.address=?, users.photo=?, performers.requisites=?, infocompanyperformers.nameCompany=?, infocompanyperformers.nameAgent=?, infocompanyperformers.surnameAgent=?, infocompanyperformers.description=? WHERE users.id=performers.users_id AND performers.id=infocompanyperformers.performers_id AND users.username=?";
	public static final String UPDATE_PASSWORD = "UPDATE allservices.users SET users.password=? WHERE users.username=?";
	
	public static final String DELETE_USER = "UPDATE allservices.users SET users.isDelete='true' WHERE users.username=?";
		
	public static final String CREATE_ORDER = "INSERT INTO allservices.orders (orders.title, orders.description, orders.subtypeSpecialization, orders.status, orders.address, orders.endDate, orders.dateOfCreating, orders.attachments, orders.users_id, orders.specialization_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	public static final String UPDATE_ORDER = "UPDATE allservices.orders SET orders.title=?, orders.description=?, orders.subtypeSpecialization=?, orders.status=?, orders.address=?, orders.endDate=?, orders.dateOfCreating=?, orders.attachments=? WHERE orders.id=?";
	public static final String DELETE_ORDER = "DELETE FROM allservices.orders WHERE orders.id=?";
	
	public static final String SELECT_PERFORMER_FOR_ORDER = "UPDATE allservices.orders SET orders.status='process', orders.performer=? WHERE orders.id=?";
	
	private SQLRequest() {
	}	
}
